'use client';
import { useEffect,useRef,useState } from 'react';
import AdminShell from './AdminShell';
import { adminStyles as s } from '../src/lib/adminStyles.js';
import { saasFetch } from '../src/lib/saas/api.js';
import { credits,idr } from '../src/lib/economicsDisplay.js';
const time=v=>v?new Date(v).toLocaleString('id-ID',{timeZone:'UTC'}):'—';
function display(k,v){if(v===null||v===undefined)return '—';if(k.endsWith('_at'))return time(v);if(k.includes('idr'))return idr(v);if(['amount','balance_after','credits','estimated_cost','available_credits','granted_credits','bonus_credits'].includes(k))return credits(v);if(typeof v==='boolean')return v?'Ya':'Tidak';return String(v);}
export function HistoryTable({title,rows,columns}) {return <section className={`${s.panel} mt-5`}><h2 className="border-b border-white/10 p-4 font-semibold">{title}</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{columns.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{rows.length?rows.map((r,i)=><tr key={r.id||i} className="border-t border-white/10">{columns.map(([key])=><td key={key}>{display(key,r[key])}</td>)}</tr>):<tr><td colSpan={columns.length} className="text-white/45">Belum ada data.</td></tr>}</tbody></table></div></section>;}
export function CustomerProfile({data}) {const w=data.workspace,e=data.economics;return <>
 <div className="mt-6 grid gap-4 sm:grid-cols-3">{[['Akun',data.account.email],['Saldo workspace',`${credits(w.balance)} kredit`],['Kredit tertahan workspace',`${credits(w.reserved)} kredit`]].map(([label,v])=><article className={s.card} key={label}><p className={s.cardLabel}>{label}</p><p className="mt-2 break-all text-lg font-semibold">{v}</p></article>)}</div>
 <p className="mt-4 text-sm text-white/60">{data.account.display_name||'Tanpa nama'} · {data.account.role} · {w.name} · Daftar {time(data.account.created_at)} UTC</p>
 <p className="mt-2 text-xs text-white/45">Generate dan sesi milik akun ini. Pembayaran, saldo, sumber kredit, dan audit milik workspace bersama. Setiap riwayat menampilkan maksimal 50 entri terbaru; invoice maksimal 100. Log sesi tersedia mulai fitur ini diaktifkan dan mencatat pembuatan/pencabutan sesi, termasuk sesi sistem.</p>
 {e&&<section className={`${s.panel} mt-5 p-5`}><h2 className="font-semibold">Economics workspace · 30 hari terakhir (UTC)</h2><p className="mt-2 text-xs text-white/45">Periode {e.since.slice(0,10)} sampai sebelum {e.until.slice(0,10)}. Biaya provider dari usage/tarif atau laporan provider, belum rekonsiliasi invoice BytePlus. Kontribusi belum merupakan laba bersih.{e.totals.simulation&&` Simulasi trial: 750 kredit = Rp149.000; pendapatan aktual ${idr(e.totals.recognizedRevenueIdr)}.`}</p><div className="mt-4 grid gap-4 sm:grid-cols-3">{[[e.totals.simulation?'Pendapatan simulasi kredit terpakai':'Pendapatan kredit terpakai',idr(e.totals.simulation?.revenueIdr??e.totals.recognizedRevenueIdr)],['Biaya provider tercatat',idr(e.totals.providerCostIdr)],[e.totals.simulation?'Kontribusi simulasi':'Kontribusi',idr(e.totals.simulation?e.totals.simulation.contributionIdr:e.totals.contributionIdr)]].map(([label,v])=><div key={label}><p className={s.cardLabel}>{label}</p><p className="mt-2 text-lg font-semibold">{v}</p></div>)}</div>{!e.totals.coverage.complete&&<p className="mt-3 text-sm text-amber-200">Data biaya, fee, atau pendapatan belum lengkap.</p>}</section>}
 <HistoryTable title="Aktivitas sesi akun (UTC)" rows={data.sessions} columns={[["action","Aktivitas"],["created_at","Waktu"]]}/>
 <HistoryTable title="Generate akun (UTC)" rows={data.jobs} columns={[["model","Model"],["status","Status"],["estimated_cost","Kredit reservasi"],["settlement_status","Settlement"],["created_at","Dibuat"]]}/>
 <HistoryTable title="Pembayaran workspace (UTC)" rows={data.payments} columns={[["order_id","Order"],["amount_idr","Harga"],["credits","Kredit"],["provider_key","Metode"],["status","Status"],["completed_at","Dibayar"]]}/>
 <HistoryTable title="Ledger kredit workspace (UTC)" rows={data.ledger} columns={[["reason","Alasan"],["amount","Perubahan"],["balance_after","Saldo setelah"],["created_at","Waktu"]]}/>
 <HistoryTable title="Sumber nilai kredit workspace" rows={data.lots} columns={[["source_type","Sumber"],["granted_credits","Diberikan"],["available_credits","Tersedia"],["amount_idr","Nilai pembelian"],["payment_fee_idr","Biaya pembayaran"]]}/>
 <HistoryTable title="Audit backoffice workspace (UTC)" rows={data.audit} columns={[["actor_email","Operator"],["target_email","Pelanggan"],["action","Aksi"],["reason","Alasan / bukti"],["created_at","Waktu"]]}/>
 </>;}
export default function BackofficeDashboard({mode}) {
 const [directory,setDirectory]=useState(null),[q,setQ]=useState(''),[search,setSearch]=useState(''),[workspaceId,setWorkspaceId]=useState(''),[customerId,setCustomerId]=useState(''),[profile,setProfile]=useState(null),[orders,setOrders]=useState([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[selected,setSelected]=useState(null);
 const [terms,setTerms]=useState({company:'',credits:'',bonus:'0',amount:'',notes:''});
 const [payment,setPayment]=useState({reference:'',paidAt:'',fee:''});
 const [grant,setGrant]=useState({credits:'',type:'trial',reason:''});
 const [cancelReason,setCancelReason]=useState('');
 const keys=useRef({});
 useEffect(()=>{let canceled=false;saasFetch(`/api/admin/backoffice?q=${encodeURIComponent(search)}`).then(d=>{if(!canceled)setDirectory(d);}).catch(e=>{if(!canceled)setError(e.message);});return()=>{canceled=true;};},[search]);
 useEffect(()=>{setProfile(null);setOrders([]);setSelected(null);setError('');if(!workspaceId)return;let canceled=false;
 const p=new URLSearchParams({workspaceId,...(customerId?{customerId}:{})});saasFetch(`/api/admin/backoffice?${p}`).then(d=>{if(canceled)return;if(customerId)setProfile(d);setOrders(d.orders||[]);}).catch(e=>{if(!canceled)setError(e.message);});return()=>{canceled=true;};},[workspaceId,customerId,revision]);
 async function submit(action,fields) {if(busy)return;setBusy(true);setError('');setNotice('');
 const payload={...fields,action,workspaceId,customerId:fields.customerId||customerId};
 const signature=JSON.stringify(payload);if(!keys.current[action]||keys.current[action].signature!==signature)keys.current[action]={signature,key:crypto.randomUUID()};
 try{await saasFetch('/api/admin/backoffice',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...payload,requestKey:keys.current[action].key})});delete keys.current[action];setRevision(v=>v+1);setNotice(action==='settle'?'Pembayaran tercatat dan kredit masuk satu kali.':action==='grant'?'Kredit non-berbayar ditambahkan dan diaudit.':action==='cancel'?'Invoice dibatalkan.':'Invoice dibuat. Kredit belum ditambahkan.');if(action==='create')setTerms({company:'',credits:'',bonus:'0',amount:'',notes:''});if(action==='grant')setGrant({credits:'',type:'trial',reason:''});}catch(e){setError(e.message);}finally{setBusy(false);}}
 const users=directory?.users||[];
 const members=users.filter(u=>u.workspaces.some(w=>w.id===workspaceId));
 const choose=(userId,w)=>{setWorkspaceId(w);setCustomerId(userId);setSelected(null);};
 const input=(label,key,state,setter,type='text',extra={})=><label className={s.label}>{label}<input className={s.field} type={type} value={state[key]} onChange={e=>setter(v=>({...v,[key]:e.target.value}))} {...extra}/></label>;
 return <AdminShell platform active={`/admin/${mode}`} title={mode==='accounts'?'Accounts & aktivitas':'Business billing'} description="Backoffice operator platform untuk akun seluruh workspace, invoice khusus, dan jejak perubahan kredit.">
 <form className={s.filters} onSubmit={e=>{e.preventDefault();setSearch(q);}}><label className={s.label}>Cari akun: nama / email<input className={s.field} value={q} maxLength={120} onChange={e=>setQ(e.target.value)}/></label><button className={s.button}>Cari akun</button></form>
 {directory?.truncated&&<p className="text-sm text-amber-200">Menampilkan 100 akun pertama. Persempit pencarian dengan email atau nama.</p>}
 {!directory&&!error&&<p className={s.loading}>Memuat akun…</p>}
 {mode==='accounts'&&directory&&<section className={`${s.panel} overflow-x-auto`}><table className="w-full text-left text-sm"><thead><tr><th>Akun</th><th>Workspace / profil</th><th>Daftar (UTC)</th></tr></thead><tbody>{users.length?users.map(u=><tr key={u.id} className="border-t border-white/10"><td>{u.email}<p className="text-xs text-white/45">{u.display_name}</p></td><td>{u.workspaces.length?u.workspaces.map(w=><button disabled={busy} key={w.id} className="mr-3 text-cyan-200" onClick={()=>choose(u.id,w.id)}>{w.name} ↗</button>):'Tanpa workspace'}</td><td>{time(u.created_at)}</td></tr>):<tr><td colSpan={3}>Tidak ada akun yang sesuai.</td></tr>}</tbody></table></section>}
 {mode==='billing'&&directory&&<div className={s.filters}><label className={s.label}>Workspace<select disabled={busy} className={s.field} value={workspaceId} onChange={e=>{setWorkspaceId(e.target.value);setCustomerId('');}}><option value="">Pilih workspace</option>{directory.workspaces.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select></label><label className={s.label}>Pelanggan / kontak invoice<select disabled={busy} className={s.field} value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Pilih anggota (cari email jika belum muncul)</option>{members.map(u=><option key={u.id} value={u.id}>{u.email}</option>)}</select></label></div>}
 {error&&<p role="alert" className={s.error}>{error}</p>}{notice&&<p role="status" className="my-4 rounded-xl border border-cyan-300/20 p-4 text-sm text-cyan-200">{notice}</p>}
 {workspaceId&&customerId&&!profile&&!error&&<p className={s.loading}>Memuat profil…</p>}
 {mode==='accounts'&&profile&&<CustomerProfile data={profile}/>}
 {mode==='billing'&&workspaceId&&<>
 {customerId&&<section className={`${s.panel} mt-5 p-5`}><h2 className="font-semibold">Buat invoice kredit khusus</h2><p className="mt-2 text-xs text-white/45">Ketentuan disimpan tetap. Kredit tidak kedaluwarsa pada versi ini. Bonus masuk dalam total kredit untuk menghitung nilai per kredit. Invoice belum berarti pembayaran diterima.</p><form className="mt-4 grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();submit('create',terms);}}>
 {input('Nama perusahaan','company',terms,setTerms,'text',{required:true,maxLength:160})}{input('Harga total (IDR)','amount',terms,setTerms,'number',{required:true,min:1,max:2000000000,step:1})}
 {input('Kredit dibeli','credits',terms,setTerms,'number',{required:true,min:1,max:10000000,step:1})}{input('Bonus kredit','bonus',terms,setTerms,'number',{required:true,min:0,max:10000000,step:1})}
 {input('Catatan kesepakatan','notes',terms,setTerms,'text',{maxLength:1000})}<p className="self-center text-sm text-white/60">Nilai per kredit: {Number(terms.credits)+Number(terms.bonus)>0?idr(Number(terms.amount)/(Number(terms.credits)+Number(terms.bonus))):'—'} (tampilan dibulatkan)</p><button disabled={busy} className={s.button}>Buat invoice</button></form></section>}
 <section className={`${s.panel} mt-5`}><h2 className="p-4 font-semibold">Invoice workspace (100 terbaru)</h2><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th>Invoice / perusahaan</th><th>Total kredit</th><th>Harga</th><th>Status</th><th>Detail</th></tr></thead><tbody>{orders.length?orders.map(o=><tr key={o.id} className="border-t border-white/10"><td>{o.invoice_number}<p className="text-xs text-white/45">{o.company_name}</p></td><td>{credits(Number(o.credits)+Number(o.bonus_credits))}</td><td>{idr(o.amount_idr)}</td><td>{o.status}</td><td><button disabled={busy} className="text-cyan-200" onClick={()=>{setSelected(o);setPayment({reference:o.payment_reference||'',paidAt:'',fee:o.payment_fee_idr??''});setCancelReason('');}}>Buka invoice</button></td></tr>):<tr><td colSpan={5}>Belum ada invoice.</td></tr>}</tbody></table></div></section>
 {selected&&<section className={`${s.panel} mt-5 p-5`}><h2 className="break-all font-semibold">{selected.invoice_number}</h2><p className="mt-2">{selected.company_name} · {selected.status}</p><p className="mt-2 text-sm text-white/60">Dibeli {credits(selected.credits)} + bonus {credits(selected.bonus_credits)} kredit · {idr(selected.amount_idr)}</p><p className="mt-2 break-words text-sm text-white/60">{selected.notes||'Tanpa catatan'}</p>{selected.status==='completed'&&<p className="mt-3 text-sm">Referensi: {selected.payment_reference} · Dibayar {time(selected.paid_at)} UTC · Fee {selected.payment_fee_idr===null?'belum diketahui':idr(selected.payment_fee_idr)}</p>}
 {selected.status==='pending'&&<><form className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();submit('settle',{customerId:selected.customer_user_id,orderId:selected.id,...payment,paidAt:new Date(payment.paidAt).toISOString()});}}><p className="text-sm text-white/60 sm:col-span-2">Catat setelah bukti pembayaran diperiksa. Ini verifikasi manual oleh operator, bukan konfirmasi otomatis bank.</p>{input('Referensi unik bukti transfer / pembayaran','reference',payment,setPayment,'text',{required:true,maxLength:160})}{input('Waktu pembayaran (zona waktu perangkat)','paidAt',payment,setPayment,'datetime-local',{required:true})}{input('Biaya pembayaran IDR (kosong = belum diketahui)','fee',payment,setPayment,'number',{min:0,max:selected.amount_idr,step:0.01})}<button disabled={busy} className={`${s.button} self-end`}>Catat pembayaran & tambah kredit</button></form><form className="mt-6 flex flex-wrap items-end gap-3" onSubmit={e=>{e.preventDefault();submit('cancel',{customerId:selected.customer_user_id,orderId:selected.id,reason:cancelReason});}}><label className={s.label}>Alasan pembatalan<input required maxLength={500} className={s.field} value={cancelReason} onChange={e=>setCancelReason(e.target.value)}/></label><button disabled={busy} className="h-10 rounded-lg border border-white/15 px-4 text-sm">Batalkan invoice</button></form></>}
 </section>}
 {customerId&&<section className={`${s.panel} mt-5 p-5`}><h2 className="font-semibold">Tambahkan kredit non-berbayar</h2><p className="mt-2 text-xs text-white/45">Masuk ke saldo workspace bersama. Nilai pendapatan Rp0. Pembelian berbayar menggunakan invoice di atas.</p><form className="mt-4 grid gap-4 sm:grid-cols-2" onSubmit={e=>{e.preventDefault();submit('grant',grant);}}>{input('Jumlah kredit','credits',grant,setGrant,'number',{required:true,min:0.000001,max:10000000,step:0.000001})}<label className={s.label}>Jenis<select className={s.field} value={grant.type} onChange={e=>setGrant(v=>({...v,type:e.target.value}))}>{['trial','bonus','compensation'].map(t=><option key={t} value={t}>{t}</option>)}</select></label>{input('Alasan pemberian','reason',grant,setGrant,'text',{required:true,maxLength:500})}<button disabled={busy} className={`${s.button} self-end`}>Tambahkan kredit & catat audit</button></form></section>}
 </>}
 </AdminShell>;
}
